src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommentRepository::class)
 */
class Comment
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $subject;

    /**
     * @ORM\Column(type="text")
     */
    private $comment;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $Status;

    /**
     * @ORM\Column(type="integer")
     */
    private $userid;

    /**
     * @ORM\Column(type="integer")
     */
    private $mountid;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $uname;

    public function getId(): ?int
    {
        return $this->id;
    }


    public function getSubject(): ?string
    {
        return $this->subject;
    }

    public function setSubject(string $subject): self
    {
        $this->subject = $subject;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }


    public function getStatus(): ?string
    {
        return $this->Status;
    }

    public function setStatus(string $Status): self
    {
        $this->Status = $Status;

        return $this;
    }

    public function getUserid(): ?int
    {
        return $this->userid;
    }

    public function setUserid(int $userid): self
    {
        $this->userid = $userid;

        return $this;
    }

    public function getMountid(): ?int
    {
        return $this->mountid;
    }

    public function setMountid(int $mountid): self
    {
        $this->mountid = $mountid;

        return $this;
    }

    public function getUname(): ?string
    {
        return $this->uname;
    }

    public function setUname(string $uname): self
    {
        $this->uname = $uname;

        return $this;
    }

}

src/Entity/Mount.php
<?php

namespace App\Entity;

use App\Repository\MountRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MountRepository::class)
 */
class Mount
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $faction;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $type;

    /**
     * @ORM\Column(type="float")
     */
    private $currency;



    /**
     * @ORM\ManyToOne(targetEntity=CurrencyType::class, inversedBy="Gold")
     */
    private $currency_type;

    /**
     * @ORM\ManyToOne(targetEntity=Expansion::class, inversedBy="mounts")
     */
    private $expansion;

    /**
     * @ORM\ManyToOne(targetEntity=Source::class)
     */
    private $source;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getFaction(): ?string
    {
        return $this->faction;
    }

    public function setFaction(string $faction): self
    {
        $this->faction = $faction;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getCurrency(): ?float
    {
        return $this->currency;
    }

    public function setCurrency(float $currency): self
    {
        $this->currency = $currency;

        return $this;
    }


    public function getCurrencyType(): ?CurrencyType
    {
        return $this->currency_type;
    }

    public function setCurrencyType(?CurrencyType $currency_type): self
    {
        $this->currency_type = $currency_type;

        return $this;
    }

    public function getExpansion(): ?Expansion
    {
        return $this->expansion;
    }

    public function setExpansion(?Expansion $expansion): self
    {
        $this->expansion = $expansion;

        return $this;
    }

    public function getSource(): ?source
    {
        return $this->source;
    }

    public function setSource(?source $source): self
    {
        $this->source = $source;

        return $this;
    }
}

templates/home/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'id': app.user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ app.user.id) }}">
    <button class="btn">Delete</button>
</form>

templates/home/_form.html.twig
{% form_theme form 'bootstrap_4_layout.html.twig' %}
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/home/change_password.html.twig
{% extends 'base.html.twig' %}
{% block title %}Change Password{% endblock %}

{% block body %}
    <div class="container">

    <h1>Change Password</h1>
    <form method="post" action="">
        <p>Ancien mot de passe</p>
        <input type="password" id="old_password" name="old_password" required="required" maxlength="30" class="form-control">
        <p>Nouveau mot de passe</p>
        <input type="password" id="new_password" name="new_password" required="required" maxlength="30" class="form-control">
        <button class="btn" type="submit" value="Change Password">Change Password</button>
    </form>
    <a href="{{ path('profile') }}">back to list</a>


</div>
{% endblock %}

templates/home/edit_profile.html.twig
{% extends 'base.html.twig' %}
{% block title %}Edit User{% endblock %}

{% block body %}
    <div class="container">

    <h1>Edit Profile</h1>

    {{ include('home/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('profile') }}">Revenir en arrière</a>



</div>
{% endblock %}

templates/home/footer.html.twig
<footer id="footer" class="top-space">
    <div class="footer2">
        <div class="container">
            <div class="row">

                <div class="col-md-6 widget">
                    <div class="widget-body">
                        <p class="simplenav">
                            <a href="{{ path('main') }}">Accueil</a> |
                            <a href="{{ path('research') }}">Recherche</a> |
                            <a href="{{ path('profile') }}">Profil</a> |
                            <b><a href="{{ path('register') }}">Inscription</a></b>
                        </p>
                    </div>
                </div>

                <div class="col-md-6 widget">
                    <div class="widget-body">
                        <p class="text-right">
                            Copyright &copy; 2020, Samuel Devadder. Designed by <a href="http://gettemplate.com/" rel="designer">gettemplate</a>
                        </p>
                    </div>
                </div>

            </div> <!-- /row of widgets -->
        </div>
    </div>

</footer>



<!-- JavaScript libs are placed at the end of the document so the pages load faster -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="/assets/js/headroom.min.js"></script>
<script src="/assets/js/jQuery.headroom.min.js"></script>
<script src="/assets/js/template.js"></script>

templates/home/forgot_password_email.html.twig
{% extends 'base.html.twig' %}

{% block title %}Recherce{% endblock %}
{% block body %}
    <div class="container">

        <ol class="breadcrumb">
            <li><a href="{{ path('main') }}">Accueil</a></li>
            <li class="active">Identification</li>
        </ol>

        <div class="row">

            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">Password Reset</h1>
                </header>

                <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <h3 class="thin text-center">Connectez-vous à votre compte</h3>
                            <p class="text-center text-muted">Enter Your E-Mail</p>
                            <hr>

                            {{ form_start(form) }}

                            <button class="btn btn-action" type="submit">Envoyer</button>
                            {{ form_end(form) }}

                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>

                </div>

            </article>
            <!-- /Article -->

        </div>
    </div>	<!-- /container -->
{% endblock %}

templates/home/head.html.twig
<link rel="shortcut icon" href="{{ asset('assets/images/gt_favicon.png') }}">

<link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
<link rel="stylesheet" href="{{ asset('assets/css/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/font-awesome.min.css') }}">

<!-- Custom styles for our template -->
<link rel="stylesheet" href="{{ asset('assets/css/bootstrap-theme.css media="screen"') }}">
<link rel="stylesheet" href="{{ asset('assets/css/main.css') }}">

<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
<script src="{{ asset('assets/js/html5shiv.js') }}"></script>
<script src="{{ asset('assets/js/respond.min.js') }}"></script>
<![endif]-->

templates/home/header.html.twig
<!-- Fixed navbar -->
<div class="navbar navbar-inverse navbar-fixed-top headroom" >
    <div class="container">
        <div class="navbar-header">
            <!-- Button for smallest screens -->
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
            <a class="navbar-brand logo" href="{{ path('main') }}"><img src="assets/images/logo_wow.png" alt="Progressus HTML5 template"></a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav pull-right">
                {% if(page == 'home') %}
                <li class="active"><a href="{{ path('main') }}">Accueil</a></li>
                <li><a href="{{ path('research') }}">Recherche</a></li>
                <li><a href="{{ path('profile') }}">Profil</a></li>
                {% if app.user %}
                    <li><a href="{{ path('app_logout') }}">Logout</a></li>
                {% else %}
                    <li><a class="btn" href="{{ path('login') }}">Identification / Inscription</a></li>
                {% endif %}


                {% elseif(page == 'research') %}
                <li><a href="{{ path('main') }}">Accueil</a></li>
                <li class="active"><a href="{{ path('research') }}">Recherche</a></li>
                <li><a href="{{ path('profile') }}">Profil</a></li>
                {% if app.user %}
                    <li><a href="{{ path('app_logout') }}">Logout</a></li>
                {% else %}
                    <li><a class="btn" href="{{ path('login') }}">Identification / Inscription</a></li>
                {% endif %}


                {% elseif(page == 'profile') %}
                <li><a href="{{ path('main') }}">Accueil</a></li>
                <li><a href="{{ path('research') }}">Recherche</a></li>
                <li class="active"><a href="{{ path('profile') }}">Profil</a></li>
                {% if app.user %}
                    <li><a href="{{ path('app_logout') }}">Logout</a></li>
                {% else %}
                    <li><a class="btn" href="{{ path('login') }}">Identification / Inscription</a></li>
                {% endif %}
                
                {% elseif(page == 'reg') %}
                <li><a href="{{ path('main') }}">Accueil</a></li>
                <li><a href="{{ path('research') }}">Recherche</a></li>
                <li><a href="{{ path('profile') }}">Profil</a></li>
                    {% if app.user %}
                        <li><a href="{{ path('app_logout') }}">Logout</a></li>
                    {% else %}
                        <li class="active"><a class="btn" href="{{ path('login') }}">Identification / Inscription</a></li>
                    {% endif %}
                {% endif %}
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</div>
<!-- /.navbar -->

<!-- Header -->
<header id="head">
    <div class="container">
        <div class="row">
            <h1 class="lead">Annuaire des montures de World of Warcraft</h1>
        </div>
    </div>
</header>
<!-- /Header -->

templates/home/identification.html.twig
{% extends 'base.html.twig' %}

{% block title %}Recherce{% endblock %}
{% block body %}
    <div class="container">

        <ol class="breadcrumb">
            <li><a href="{{ path('main') }}">Accueil</a></li>
            <li class="active">Identification</li>
        </ol>

        <div class="row">

            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">Identification</h1>
                </header>

                <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <h3 class="thin text-center">Connectez-vous à votre compte</h3>
                            <p class="text-center text-muted">Si vous n'avez pas encore de compte, veuillez-vous <a href="{{ path('register') }}" class="up">Inscrire</a>, afin de pouvoir vous connecter.</p>
                            <hr>

                            <form method="post" action="{{ path('login') }}">
                                <div class="top-margin">
                                    <label>Email <span class="text-danger">*</span></label>
                                    <input type="text" name="email" id="inputEmail" class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>Mot de passe <span class="text-danger">*</span></label>
                                    <input type="password" name="password" id="inputPassword" class="form-control">
                                </div>

                                <hr>
                                <input type="hidden" name="_csrf_token"
                                       value="{{ csrf_token('authenticate') }}"
                                >
                                <div class="row">
                                    <div class="col-lg-8">
                                        <b><a href="{{ path('forgot_pwd') }}">Mot de passe oublié ?</a></b>
                                    </div>
                                    <div class="col-lg-4 text-right">
                                        <button class="btn btn-action" type="submit">Envoyer</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>

                </div>

            </article>
            <!-- /Article -->

        </div>
    </div>	<!-- /container -->
{% endblock %}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Home{% endblock %}
{% block body %}
<!-- Intro -->
<div class="container text-center">
    <br> <br>
    <h2 class="thin margin-bot">Le meilleur endroit ou trouver une monture à votre fessier</h2>
</div>
<!-- /Intro-->

<!-- Highlights - jumbotron -->

<div class="container text-justify">
    <div class="col-sm-12 margin-bot">
        <img src="assets/images/annuaire_home.jpg" alt="accueil">
    </div>

    <div class="col-sm-12">
        <p>Lorem ipsum Lorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem
            Lorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem
            Lorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem
            Lorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem
            Lorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsum Lorem
            Lorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem
            Lorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem
            Lorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem
            Lorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem
            Lorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem
            Lorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem
            Lorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem
            Lorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem
            Lorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem
            Lorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem.
        </p>
    </div>
</div>


<div class="jumbotron top-space">
    <div class="container">

        <h3 class="text-center thin">Dernières montures ajoutée</h3>

        <div class="row">
            {% for latest_mount in latest_mounts %}
                <div class="col-md-3 col-sm-6 highlight">
                    <div class="h-caption"><h4>{{ latest_mount.name }}</h4></div>
                    <div class="h-body text-center">
                        <a href="mount/{{ latest_mount.id }}">
                            <img src="{{ asset('assets/uploads/images/' ~latest_mount.image ) }}" alt="accueil">
                        </a>
                    </div>
                </div>
            {% endfor %}

        </div> <!-- /row  -->

    </div>
</div>
<!-- /Highlights -->


{% endblock %}

templates/home/inscription.html.twig
{% extends 'base.html.twig' %}

{% block title %}Inscription{% endblock %}
{% block body %}
    <!-- container -->
    <div class="container">

        <ol class="breadcrumb">
            <li><a href="{{ path('main') }}">Accueil</a></li>
            <li class="active">Inscription</li>
        </ol>

        <div class="row">

            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">Inscription</h1>
                </header>

                <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <h3 class="thin text-center">Enregistrer un nouveau compte</h3>
                            <p class="text-center text-muted">Si vous avez déjà un compte, veuillez-vous <a href="/" class="up">Identifier</a>, afin de pouvoir vous connecter. </p>
                            <hr>
                            <form name="user" method="post" class="user" enctype="multipart/form-data">
                                
                                <div class="top-margin">
                                    <label>Pseudo</label>
                                    <input type="text" id="registration_form_uname" name="registration_form[uname]" required="required" class="form-control">
                                </div>

                                <div class="top-margin">
                                    <label>Adresse email<span class="text-danger">*</span></label>
                                    <input type="text" id="registration_form_email" name="registration_form[email]" required="required" class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>Mot de passe<span class="text-danger">*</span></label>
                                    <input type="password" id="registration_form_plainPassword" name="registration_form[plainPassword]" required="required"  class="form-control">
                                </div>
                                <div class="top-margin">
                                    {{ form_row(registrationForm.description) }}</div>
                                <hr>
                                {{ form_row(registrationForm.image) }}
                                <div class="row">
                                    <div class="col-lg-8">
                                        <label class="checkbox">
                                            {{ form_row(registrationForm.agreeTerms) }}

                                        </label>
                                    </div>
                                    <div class="col-lg-4 text-right">
                                        {{ form_row(registrationForm._token) }}
                                        <button class="btn btn-action" type="submit">Envoyer</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>

                </div>

            </article>
            <!-- /Article -->

        </div>
    </div>	<!-- /container -->
{% endblock %}

templates/home/monture_profile.html.twig
{% extends 'base.html.twig' %}

{% block title %}Home{% endblock %}
{% block body %}
    <!-- container -->
    <div class="container">

        <ol class="breadcrumb">
            <li><a href="{{ path('main') }}">{{ mount.name }}</a></li>
            <li class="active">Nom de la monture</li>
        </ol>

        <div class="row">
            <article class="maincontent">
                <header class="page-header">
                    <h1 class="page-title">{{ mount.name }}</h1>
                </header>
                <div class="">
                    <div class="col-sm-6">

                        <p class="text-justify">{{ mount.description }}</div>
                    <div class="col-sm-6 text-center">
                        <img src="{{ asset('assets/uploads/images/' ~mount.image) }}" class="col-sm-12" alt="mount_profil">
                        <p class="col-sm-6 text-center top-margin">{{ mount.name }}</p>
                        <p class="col-sm-6 text-center top-margin">{{ mount.faction }}</p>
                        <p class="col-sm-6 text-center">{{ mount.type }}</p>
                        <p class="col-sm-6 text-center">{{ mount.expansion }}</p>
                        <p class="col-sm-6 text-center">{{ mount.source }}</p>
                        <p class="col-sm-6 text-center">{{ mount.currency }} {{ mount.currencyType }}</p>
                    </div>

                </div>
            </article>
        </div>
        <div class="row">
            <div class="col-sm-10 col-sm-offset-1">
                <div class="page-header">
                    <h3 class="reviews">Leave your comment</h3>
                </div>
                {% if app.user %}
                <form action="{{ path('mount', {'id': mount.id}) }}" method="post">
                <div class="contact-form">
                    <div class="form-group">
                        <label for="comment_subject" class="required"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Subject</font></font></label>
                        <input type="text" id="comment_subject" name="comment[subject]" required="required" maxlength="50" class="form-control"></div>
                    <div class="form-group">
                        <div class="">
                            <textarea id="comment_comment" name="comment[comment]" class="form-control" rows="5"></textarea>
                        </div>
                        {{ form_row(form._token) }}
                        <button type="submit" class="btn btn-default">Submit</button>
                    </div>
                </div>
                </form>
                {% else %}
                    <li>
                        <a href="{{ path('login') }}"><i class="icon-envelope-alt"></i>Si vous voulez ajouter un commentaire, veuillez vous connecter</a>
                    </li>
                {% endif %}
                <div class="comment-tabs">
                    <ul class="nav nav-tabs" role="tablist">
                        <li class="active"><a href="#" role="tab" data-toggle="tab">
                                <h4 class="reviews text-capitalize">Comments</h4>
                            </a></li>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane active" id="comments-logout">
                            <ul class="media-list">
                                {% for comment in comments %}
                                <li class="media">
                                    <div class="media-body">
                                        <div class="well well-lg">
                                            <h4 class="media-heading text-uppercase reviews">{{ comment.uname }}</h4>
                                            <ul class="media-date text-uppercase reviews list-inline">
                                                <li>{{ comment.createdAt|date('Y-m-d H:i') }}</li>
                                            </ul>
                                            <h5>{{ comment.subject }}</h5>
                                            <p class="media-comment">
                                                {{comment.comment}}
                                            </p>
                                        </div>
                                    </div>
                                </li>
                                {% endfor %}

                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>	<!-- /container -->
{% endblock %}

templates/home/profile.html.twig
{% extends 'base.html.twig' %}

{% block title %}Home{% endblock %}
{% block body %}
    <!-- container -->
    <div class="container">

        <ol class="breadcrumb">
            <li><a href="{{ path('main') }}">Accueil</a></li>
            <li class="active">Profil</li>
        </ol>

        <div class="row">

            <!-- Article main content -->
            <article class="maincontent">
                <header class="page-header">
                    <h1 class="page-title">Bonjour ({{ app.user.uname }})</h1>
                </header>

                <div>
                    <div class="col-sm-4">
                        <img src="{{ asset('assets/uploads/images/' ~app.user.image) }}" alt="profil">
                    </div>
                    <div class="col-sm-8 text-justify">
                        <a color="#000" href="{{ path('edit_profile') }}">Edit Profile
                        </a>
                        <a color="#000" href="{{ path('change_password') }}">Change Password
                        </a>
                        <p class="top-margin">Description de ({{app.user.uname}})</p>
                        <p>{{ app.user.description }}</p>

                        <p>Rôle : Novice</p>

                    </div>
                </div>
            </article>
        </div>
    </div>	<!-- /container -->
{% endblock %}